/* eslint-disable @next/next/no-img-element -- local guide asset is already compressed */
import Link from "../../components/document-link";
import { Download } from "lucide-react";
import { PageHero, Section, SectionTitle } from "../../components/ui";
import { createPageMetadata } from "../../content/metadata";

export const metadata=createPageMetadata({title:"Educação ambiental",description:"Butiazais, biodiversidade costeira e turismo responsável em Imbituba.",path:"/educacao-ambiental"});

export default function Educacao(){return <main>
  <PageHero kicker="Aprender com o território" title="Natureza é cultura viva" intro="Dunas, lagoas, praias, oceanos e butiazais contam histórias e sustentam formas de vida." tone="green"/>
  <Section className="environment-lead"><div className="environment-photo"><img src="/images/guia/butia.webp" alt="Butiá em seu ambiente costeiro" width="468" height="1064" loading="lazy" decoding="async"/><small>Fotografia: Cláudio Moreira Lima / Morlima Produções · Guia oficial</small></div><div><SectionTitle kicker="Espécie símbolo" title="Butia catarinensis"/><div className="prose"><p>Também chamado de butiá-da-praia ou coqueiro-butiazeiro, pertence à família Arecaceae. Segundo o guia oficial, esta palmeira é exclusiva do litoral sul do Brasil. Em Santa Catarina, concentra-se especialmente em Imbituba e Laguna; também há áreas remanescentes em ambientes costeiros do Rio Grande do Sul.</p><p>Ela cresce em solos arenosos de áreas costeiras, dunas, restingas e bordas de Mata Atlântica. Frutos, folhas e paisagem aproximam biodiversidade, culinária, artesanato e memória.</p></div><div className="eco-facts"><article><b>1—4 m</b><span>altura indicada no guia</span></article><article><b>200+</b><span>anos de vida</span></article><article><b>Vulnerável</b><span>em Santa Catarina</span></article></div><a className="button ghost" href="/documentos/guia-caminho-dos-butiazais.pdf#page=6" target="_blank" rel="noreferrer"><Download aria-hidden="true"/> Consultar as páginas 6–9 do guia</a></div></Section>
  <Section className="sand"><SectionTitle kicker="Botânica e ecologia" title="Uma palmeira moldada pelo litoral"/><div className="three-col"><article><h3>Forma e frutos</h3><p>Folhas longas em forma de pena, tronco de crescimento lento e frutos arredondados ou alongados em tons amarelos, alaranjados ou avermelhados.</p></article><article><h3>Vida na restinga</h3><p>O butiá oferece abrigo e alimento para aves, insetos e pequenos mamíferos. Seus frutos atraem fauna que contribui para dispersar sementes.</p></article><article><h3>Proteção do solo</h3><p>O sistema radicular ajuda a fixar dunas e a reduzir a erosão, reforçando a proteção dos ambientes costeiros.</p></article></div></Section>
  <Section><SectionTitle kicker="Cultura e modos de fazer" title="Do fruto à memória coletiva"/><div className="theme-list compact-themes"><article><span>01</span><div><h2>Gastronomia</h2><p>Polpa usada em geleias, licores, doces, sorvetes e sucos. Em 2024, a Lei Estadual nº 19.013 declarou a Cachaça com Butiá integrante do Patrimônio Cultural Imaterial de Santa Catarina.</p></div></article><article><span>02</span><div><h2>Artesanato</h2><p>Folhas secas são trançadas em esteiras, bolsas, cestos e outros objetos; sementes e frutos também aparecem em produtos artesanais.</p></div></article><article><span>03</span><div><h2>Tradições</h2><p>A espécie está presente em histórias, práticas comunitárias, feiras, celebrações e narrativas do litoral catarinense.</p></div></article><article><span>04</span><div><h2>Turismo cultural</h2><p>Butiazais, produtos locais e o próprio Caminho formam oportunidades de educação, visitação responsável e valorização do território.</p></div></article></div></Section>
  <Section className="threat-section"><SectionTitle kicker="Ameaças documentadas" title="O que pressiona os butiazais"/><div className="threat-grid"><article><b>01</b><h3>Expansão urbana</h3><p>Ocupação desordenada e crescimento imobiliário comprimem áreas onde a espécie ocorre.</p></article><article><b>02</b><h3>Uso inadequado do solo</h3><p>Substituição de áreas naturais e práticas pouco cuidadosas comprometem a regeneração.</p></article><article><b>03</b><h3>Desconhecimento</h3><p>A falta de conscientização sobre o valor ecológico e cultural reduz a proteção cotidiana.</p></article><article><b>04</b><h3>Mudanças climáticas</h3><p>Alterações no regime de chuvas e temperaturas podem afetar crescimento e reprodução.</p></article></div></Section>
  <Section className="dark"><SectionTitle kicker="Práticas" title="Turismo responsável"/><div className="three-col"><article><h3>Observe sem retirar</h3><p>Deixe plantas, sementes e elementos naturais onde estão.</p></article><article><h3>Reduza seu impacto</h3><p>Leve seus resíduos e respeite trilhas, dunas e áreas sensíveis.</p></article><article><h3>Escute o lugar</h3><p>Valorize orientações de comunidades, condutores e instituições locais.</p></article></div><p className="environment-cta"><Link className="button glass" href="/caminho-dos-butiazais">Explorar os 14 pontos →</Link></p></Section>
</main>}
