/* eslint-disable @next/next/no-img-element -- local guide image is pre-compressed and dimensioned */
import { ArrowUpRight } from "lucide-react";
import { PageHero, Section, SectionTitle } from "../../components/ui";
import { timeline } from "../../content/site";
import { createPageMetadata } from "../../content/metadata";

export const metadata=createPageMetadata({title:"O Centro",description:"Conheça a história e as áreas de atuação do Mariscão da Zimba.",path:"/sobre"});

export default function Sobre(){return <main>
  <PageHero kicker="Desde 2008 · Imbituba" title="O Mariscão da Zimba" intro="Uma organização cultural viva, construída na relação entre comunidade, memória, natureza e território."/>
  <Section className="split"><SectionTitle kicker="Quem somos" title="Cultura feita de presença"/><div className="prose"><p>O Centro Cultural e Turístico Mariscão da Zimba é uma organização cultural sem fins lucrativos fundada em 27 de maio de 2008. Sua trajetória reúne projetos culturais, literários, artesanais, educativos, comunitários e de valorização territorial.</p><p>Documentos públicos também usam as denominações Associação Cultural e Carnavalesca Mariscão da Zimba e Associação Cultural Mariscão da Zimba. O portal trata essas referências como parte da mesma trajetória institucional.</p><a className="button text" href="https://www.imbituba.sc.leg.br/proposicoes/Mocoes/0/1/0/5064" target="_blank" rel="noreferrer">Ler a homenagem da Câmara <ArrowUpRight aria-hidden="true"/></a></div></Section>
  <Section className="dark"><SectionTitle kicker="Síntese editorial" title="Nossa missão" intro="Preservar, registrar, compartilhar e fortalecer a cultura, a memória, a natureza e os saberes das comunidades do litoral catarinense."/><p className="note">Esta frase sintetiza a atuação documentada do Centro; não é transcrição de estatuto.</p></Section>
  <Section><SectionTitle kicker="Trajetória" title="Uma história em movimento"/><div className="timeline">{timeline.map(([year,text])=><article key={year}><time>{year}</time><p>{text}</p></article>)}</div></Section>
  <Section className="split sand"><SectionTitle kicker="Reconhecimento estadual · 2024" title="Cachaça com Butiá: o que a lei realmente reconhece"/><div className="prose"><p>A Lei Estadual nº 19.013, sancionada em 24 de julho de 2024, declarou a <strong>Cachaça com Butiá</strong> integrante do Patrimônio Cultural Imaterial do Estado de Santa Catarina, por representar os sabores e fazeres do litoral catarinense.</p><p>O texto final da lei não cita uma marca. A participação do Mariscão da Zimba aparece na justificativa do Projeto de Lei nº 0169/2023, que registra a atuação do Centro na preservação do butiá e o lançamento da cachaça com butiá Mariscão da Zimba em articulação com famílias da comunidade.</p><a className="button text" href="https://leis.alesc.sc.gov.br/ato-normativo/22514" target="_blank" rel="noreferrer">Ler a Lei nº 19.013/2024 <ArrowUpRight aria-hidden="true"/></a><a className="button text" href="https://portalelegis.alesc.sc.gov.br/documentos/zJyx0/download" target="_blank" rel="noreferrer">Ler a justificativa do projeto <ArrowUpRight aria-hidden="true"/></a></div></Section>
  <Section className="split sand"><SectionTitle kicker="Cultura Viva" title="Um Ponto de Cultura em Imbituba"/><div className="prose"><p>O Centro integra a rede da Política Nacional Cultura Viva. Sua ficha no Cadastro Nacional de Pontos e Pontões de Cultura identifica a atuação comunitária em Imbituba.</p><a className="button text" href="https://culturaviva.cultura.gov.br/agente/16009841/" target="_blank" rel="noreferrer">Ver cadastro oficial <ArrowUpRight aria-hidden="true"/></a></div></Section>
  <Section><SectionTitle kicker="Pessoas e conexões" title="Uma rede de saberes e colaboração" intro="As funções são contextualizadas pela data da fonte para não transformar registros históricos em cargos atuais."/><div className="people-grid"><article><h3>Célio de Oliveira</h3><p>Fundador, produtor e articulador cultural associado à Rota Açoriana, ao Caminho dos Butiazais e ao NEA/UFSC.</p><a href="https://rededasartes.cultura.gov.br/agente/15293/" target="_blank" rel="noreferrer">Cadastro Rede das Artes →</a></article><article><h3>Núcleo de Estudos Açorianos</h3><p>O Mariscão participa da rede do NEA/UFSC, conexão institucional ligada à preservação e difusão da cultura de base açoriana.</p><a href="https://nea.ufsc.br/conselho-deliberativo/" target="_blank" rel="noreferrer">Consultar NEA/UFSC →</a></article><figure className="people-photo"><img src="/images/guia/mariscao-da-zimba.webp" srcSet="/images/guia/mariscao-da-zimba-480.webp 480w, /images/guia/mariscao-da-zimba-960.webp 960w, /images/guia/mariscao-da-zimba.webp 1019w" sizes="(max-width: 900px) 100vw, 34vw" width="1019" height="525" alt="Interior do Centro Cultural e Turístico Mariscão da Zimba" loading="lazy" decoding="async"/><figcaption><span>Espaço de memória e encontro</span><small>Fotografia: Cláudio Moreira Lima / Morlima Produções</small></figcaption></figure></div></Section>
</main>}
