/* eslint-disable @next/next/no-img-element -- local assets are compressed and dimensioned */
import Link from "../../components/document-link";
import { ArrowUpRight, Download, Play } from "lucide-react";
import { Section, SectionTitle } from "../../components/ui";
import { guideImageSrcSet, landmarks } from "../../content/landmarks";
import { createPageMetadata } from "../../content/metadata";

export const metadata=createPageMetadata({title:"Caminho dos Butiazais",description:"Roteiro cultural, turístico e ambiental por 14 pontos de Imbituba.",path:"/caminho-dos-butiazais",image:"/images/official/butiazais-hero-restored.webp",imageWidth:1672,imageHeight:941});

export default function Caminho(){return <main className="route-page">
  <section className="route-hero"><img src="/images/official/butiazais-hero-restored.webp" alt="Vista aérea dos butiazais e do litoral de Imbituba" width="1672" height="941" fetchPriority="high" decoding="async"/><div><p className="eyebrow">Roteiro cultural e turístico · Imbituba</p><h1>Caminho dos<br/><em>Butiazais</em></h1><p>Uma jornada pela cultura e natureza de Imbituba, guiada por paisagens, memórias e comunidades.</p><div className="actions"><a className="button primary" href="/documentos/guia-caminho-dos-butiazais.pdf" target="_blank" rel="noreferrer"><Download aria-hidden="true"/> Abrir guia oficial</a><a className="button glass" href="#documentario"><Play aria-hidden="true"/> Assistir ao filme</a></div></div><span className="hero-seal">14<br/><small>pontos</small></span><small className="hero-credit">Frame restaurado do documentário oficial</small></section>
  <Section className="split route-intro"><SectionTitle kicker="O percurso" title="Muito além de paisagens encantadoras"/><div className="prose"><p>O Caminho dos Butiazais integra turismo, cultura e preservação ambiental, valorizando a herança cultural das comunidades de Imbituba e os ecossistemas costeiros.</p><p>Em cada etapa, o <i>Butia catarinensis</i> aparece como protagonista ou presença silenciosa — símbolo de resistência e do vínculo das comunidades com a terra.</p><p className="source-note">Texto baseado no Guia Caminho dos Butiazais, publicação oficial do projeto.</p></div></Section>
  <section className="map-panel"><div><p className="eyebrow">Mapa do guia oficial</p><h2>Do sul de Ibiraquera à Praia da Vila</h2><p>Uma visão geral dos 14 pontos do roteiro. Use o mapa como orientação cultural; confirme acessos, clima, maré e condições locais antes de percorrer trilhas e costões.</p><a className="button text" href="/documentos/guia-caminho-dos-butiazais.pdf#page=10" target="_blank" rel="noreferrer">Abrir o mapa no PDF <ArrowUpRight aria-hidden="true"/></a></div><figure><img src="/images/official/mapa-caminho-dos-butiazais.webp" srcSet="/images/official/mapa-caminho-dos-butiazais-640.webp 640w, /images/official/mapa-caminho-dos-butiazais.webp 971w" sizes="(max-width: 900px) calc(100vw - 44px), 50vw" alt="Mapa oficial do Caminho dos Butiazais com os 14 pontos em Imbituba" width="971" height="890" loading="lazy" decoding="async"/><figcaption>Mapa publicado no Guia Caminho dos Butiazais · página 10</figcaption></figure></section>
  <section className="route-index"><header><p className="eyebrow">O roteiro oficial</p><h2>14 encontros<br/>com o território</h2></header><div className="route-cards">{landmarks.map((landmark,index)=><Link className="route-card" href={`/caminho-dos-butiazais/${landmark.slug}`} key={landmark.slug}><img src={landmark.image} srcSet={guideImageSrcSet(landmark.image,landmark.imageWidth)} sizes="(max-width: 900px) calc(100vw - 44px), 50vw" alt="" width={landmark.imageWidth} height={landmark.imageHeight} loading="lazy" decoding="async"/><span className="route-no">{String(index+1).padStart(2,"0")}</span><div><small>{landmark.category}</small><h3>{landmark.name}</h3><p>{landmark.description}</p><b>Conhecer <ArrowUpRight aria-hidden="true"/></b></div></Link>)}</div></section>
  <Section className="butia-section"><div className="butia-title"><p className="eyebrow">Espécie símbolo</p><h2><i>Butia</i><br/>catarinensis</h2></div><div className="butia-copy"><p>Palmeira endêmica do Brasil, encontrada nas restingas de Santa Catarina e do Rio Grande do Sul. Seus frutos, folhas e presença na paisagem conectam biodiversidade, culinária, artesanato e memória.</p><div className="fact-grid"><span><b>Endêmica</b> do Brasil</span><span><b>Restingas</b> de SC e RS</span><span><b>Em Perigo (EN)</b> na lista estadual</span></div><p className="source-note">A classificação estadual segue a Resolução CONSEMA nº 51/2014. O guia impresso usa “vulnerável”; nesta página prevalece a lista oficial.</p><a className="button text" href="https://portal.doe.sea.sc.gov.br/repositorio/2014/20141223/Jornal/1090.pdf" target="_blank" rel="noreferrer">Consultar a lista estadual <ArrowUpRight aria-hidden="true"/></a></div></Section>
  <section id="documentario" className="film-section"><div><p className="eyebrow">Documentário oficial · 2025</p><h2>Conhecendo o Caminho dos Butiazais</h2><p>Produção realizada com recursos da Lei Paulo Gustavo e publicada pelo canal oficial do projeto.</p><a className="button glass" href="https://www.youtube.com/watch?v=pAz-L5ygrUc" target="_blank" rel="noreferrer">Abrir no YouTube <ArrowUpRight aria-hidden="true"/></a></div><div className="video-wrap"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/pAz-L5ygrUc" title="Documentário Conhecendo o Caminho dos Butiazais" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/></div></section>
  <Section className="care-section"><SectionTitle kicker="Visitação consciente" title="Cuide do caminho enquanto caminha"/><div className="three-col"><article><h3>Respeite o território</h3><p>Siga orientações locais, não deixe resíduos e não retire plantas ou materiais naturais.</p></article><article><h3>Valorize as comunidades</h3><p>Escute quem vive no lugar e dê preferência a experiências e produtores locais.</p></article><article><h3>Planeje a visita</h3><p>Condições de acesso mudam. Verifique clima, maré e orientações atuais.</p></article></div></Section>
</main>}
