import { ArrowUpRight, BookOpen } from "lucide-react";
import Link from "../../components/document-link";
import { CoastalVideoGallery } from "../../components/coastal-videos";
import { PageHero, Section, SectionTitle } from "../../components/ui";
import { coastalChannel, coastalVideos, coastalSelectionCheckedOn, portoVideos, otherCoastalVideos } from "../../content/coastal-videos";
import { createPageMetadata } from "../../content/metadata";
export const metadata=createPageMetadata({title:"Praias em vídeo",description:"Criações audiovisuais de Célio de Oliveira sobre as praias, lagoas e ilhas de Imbituba, com a Praia do Porto em destaque.",path:"/praias-em-video"});
export default function PraiasEmVideo(){return <main className="coastal-page">
  <PageHero kicker="Mariscão · Olhares para o litoral" title="Praias em vídeo" intro={`Paisagem, comunidade e memória em ${coastalVideos.length} criações audiovisuais de Célio de Oliveira sobre praias, lagoas e ilhas, publicadas no canal Mariscão da zimba.`} tone="blue"/>
  <nav className="coastal-page-nav" aria-label="Navegação da seleção audiovisual"><a href="#praia-do-porto">Praia do Porto</a><a href="#outras-paisagens">Outras paisagens</a><a href={coastalChannel.url} target="_blank" rel="noopener noreferrer">Conheça o canal <ArrowUpRight aria-hidden="true"/></a></nav>
  <section className="coastal-feature" id="praia-do-porto" aria-labelledby="porto-selection-title"><header className="coastal-heading"><div><p className="eyebrow">01 — Praia do Porto</p><h2 id="porto-selection-title">Entre o mar e a memória.</h2></div><p>Três olhares para um mesmo território: a pesca artesanal, o canto norte e a paisagem do mirante. Escolha um vídeo para assistir aqui ou abra diretamente no YouTube.</p></header><CoastalVideoGallery videos={portoVideos} id="porto-selection"/></section>
  <section className="coastal-feature coastal-feature-light" id="outras-paisagens" aria-labelledby="other-coasts-title"><header className="coastal-heading"><div><p className="eyebrow">02 — Outras paisagens</p><h2 id="other-coasts-title">Imbituba, além do horizonte.</h2></div><p>Do Rosa a Itapirubá, passando pelo Luz, Vermelha, Ribanceira, Amores e Barra de Ibiraquera: praias, lagoas, ilhas e panoramas do litoral compõem esta seleção do canal.</p></header><CoastalVideoGallery videos={otherCoastalVideos} id="coastal-selection"/></section>
  <Section className="sand split coastal-context"><SectionTitle kicker="Para continuar a descoberta" title="Um olhar artístico. Um território real."/><div className="prose"><p>Os vídeos e suas capas são materiais de apresentação do criador, não substituem o guia, fontes históricas ou informações atualizadas de visitação. As sinopses descrevem os temas das publicações; não afirmam que suas imagens sejam registros documentais.</p><p>Para conhecer os lugares com contexto e referências, consulte o Caminho dos Butiazais. A seleção audiovisual foi conferida em {coastalSelectionCheckedOn}; novas publicações no YouTube não entram automaticamente no portal.</p><div className="actions"><Link className="button text" href="/caminho-dos-butiazais/mirante-da-praia-do-porto"><BookOpen aria-hidden="true"/>Conheça o mirante</Link><Link className="button text" href="/caminho-dos-butiazais">Explore o roteiro <ArrowUpRight aria-hidden="true"/></Link></div></div></Section>
</main>}
