/* eslint-disable @next/next/no-img-element -- local guide assets are already compressed */
import type { Metadata } from "next";
import Link from "../../../components/document-link";
import { notFound, permanentRedirect } from "next/navigation";
import { ArrowLeft, ArrowRight, BookOpen, Download } from "lucide-react";
import { getLandmark, guideImageSrcSet, landmarks, legacyLandmarkRedirects } from "../../../content/landmarks";
import { createPageMetadata } from "../../../content/metadata";
import { Breadcrumb, Section } from "../../../components/ui";

export async function generateStaticParams(){return landmarks.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const landmark=getLandmark((await params).slug);if(!landmark)return{};return createPageMetadata({title:landmark.name,description:landmark.description,path:`/caminho-dos-butiazais/${landmark.slug}`,image:landmark.image,imageWidth:landmark.imageWidth,imageHeight:landmark.imageHeight})}

function GuideGroup({title,items}:{title:string;items?:string[]}){if(!items?.length)return null;return <article><h3>{title}</h3><ul>{items.map((item)=><li key={item}>{item}</li>)}</ul></article>}

export default async function LandmarkPage({params}:{params:Promise<{slug:string}>}){const requestedSlug=(await params).slug;if(legacyLandmarkRedirects[requestedSlug])permanentRedirect(`/caminho-dos-butiazais/${legacyLandmarkRedirects[requestedSlug]}`);const landmark=getLandmark(requestedSlug);if(!landmark)notFound();const index=landmarks.indexOf(landmark);const prev=landmarks[index-1];const next=landmarks[index+1];const guidePageLabel=landmark.guidePages.length>1?`${landmark.guidePages[0]}–${landmark.guidePages.at(-1)}`:`${landmark.guidePages[0]}`;return <main className="landmark-page">
  <Breadcrumb items={[["Início","/"],["Caminho dos Butiazais","/caminho-dos-butiazais"],[landmark.name]]}/>
  <section className="landmark-hero"><div className={`landmark-image ${landmark.imageHeight>landmark.imageWidth?"portrait":"landscape"}`}><img src={landmark.image} srcSet={guideImageSrcSet(landmark.image,landmark.imageWidth)} sizes="(max-width: 900px) calc(100vw - 44px), 50vw" alt={`Registro de ${landmark.name} publicado no guia oficial`} width={landmark.imageWidth} height={landmark.imageHeight} fetchPriority="high" decoding="async"/><small>Cláudio Moreira Lima / Morlima Produções</small></div><div className="landmark-title"><span>{String(index+1).padStart(2,"0")} / 14</span><p>{landmark.category}</p><h1>{landmark.name}</h1><p className="lead">{landmark.description}</p>{landmark.aliases?.length&&<p className="landmark-aliases">Também conhecida como {landmark.aliases.join(" e ")}.</p>}</div></section>
  <Section className="landmark-story"><div><p className="eyebrow">Sobre este lugar</p><h2>História,<br/>paisagem e<br/>presença</h2></div><div className="prose"><p>{landmark.longDescription}</p><div className="landmark-facts">{landmark.facts.map((fact,factIndex)=><article key={fact}><span>0{factIndex+1}</span><p>{fact}</p></article>)}</div><a className="button ghost landmark-source" href={`/documentos/guia-caminho-dos-butiazais.pdf#page=${landmark.guidePages[0]}`} target="_blank" rel="noreferrer"><Download aria-hidden="true"/> Abrir páginas {guidePageLabel} do guia</a></div></Section>
  <Section className="landmark-guide"><div className="content-heading"><p className="eyebrow">Planeje com a fonte oficial</p><h2>Informações do guia</h2><p>Dados publicados em 2025. Antes de sair, confirme condições atuais de acesso, clima, maré, serviços e horários.</p></div><div className="guide-detail-grid">{landmark.location&&<GuideGroup title="Localização" items={[landmark.location]}/>}<GuideGroup title="Como chegar" items={landmark.access}/><GuideGroup title="O que fazer" items={landmark.activities}/><GuideGroup title="Gastronomia" items={landmark.gastronomy}/><GuideGroup title="Melhor época" items={landmark.bestTime}/><GuideGroup title="Estrutura e serviços" items={landmark.services}/><GuideGroup title="Cuidados e alertas" items={landmark.tipsAlerts}/><GuideGroup title="Conservação" items={landmark.conservation}/><GuideGroup title="Curiosidades" items={landmark.curiosities}/></div>{landmark.operationalNotice&&<p className="operational-notice">{landmark.operationalNotice}</p>}</Section>
  <Section className="landmark-themes"><div><p className="eyebrow">Temas culturais</p><div className="tag-row">{landmark.culturalThemes.map((theme)=><span key={theme}>{theme}</span>)}</div></div><div><p className="eyebrow">Temas ambientais</p><div className="tag-row">{landmark.environmentalThemes.map((theme)=><span key={theme}>{theme}</span>)}</div></div></Section>
  <section className="visit-note"><BookOpen aria-hidden="true"/><div><p className="eyebrow">Antes de conhecer</p><h2>{landmark.visitNote}</h2><p>Informações extraídas do guia oficial. Condições locais podem mudar; faça uma verificação atual antes de sair.</p></div></section>
  <nav className={`landmark-nav ${!prev?"only-next":""}`} aria-label="Navegação entre os pontos">{prev&&<Link href={`/caminho-dos-butiazais/${prev.slug}`}><ArrowLeft aria-hidden="true"/><span>Anterior<small>{prev.name}</small></span></Link>}{next?<Link href={`/caminho-dos-butiazais/${next.slug}`}><span>Próximo<small>{next.name}</small></span><ArrowRight aria-hidden="true"/></Link>:<Link href="/caminho-dos-butiazais"><span>Voltar ao roteiro<small>Todos os 14 pontos</small></span><ArrowRight aria-hidden="true"/></Link>}</nav>
</main>}
